### ISSUE TITLE
Release PHP 8 support

### ISSUE THREAD

**Issue by Slamdunk** [laminas/laminas-server#24]
Hi, https://github.com/laminas/laminas-server/pull/23 brought support for PHP 8, but it's locked to `3.0.x` branch which I don't know how soon will be released.

I'd like to ask for an estimate **of work** remaining to have a `v3` release, or the willingness to merge a similar PR for `v2` branch.

**Comment by weierophinney** [comment]
Pinging @arueckauer as he was working on these various RPC-related repositories last summer and autumn...

**Comment by arueckauer** [comment]
My ultimate goal is/was to bring `laminas-json-server` in compliance with [JSON-RPC 2.0](https://www.jsonrpc.org/specification) and add middleware-compatibilty. The latter part requires a breaking change on the base - this component - but would be beneficial to all the RPC components with an upgrade in them.

Although I personally would like to see these changes being implemented, I underesimated the amount of required work. Plus time was very limited the past several months. At the moment I cannot give an estimate on when I can complete the desired changes.

@weierophinney Would it be possible to release a PHP 8 compatible version of this prior to the mentioned changes?

**Comment by Slamdunk** [comment]
Well, I can easily backport PHP8 support to v2 then, I don't want to push a v3 release with one leg broken.

**Comment by Slamdunk** [comment]
Backport proposed in https://github.com/laminas/laminas-server/pull/25

**Comment by ihor-sviziev** [comment]
This was added in release 2.10.0 https://github.com/laminas/laminas-server/releases/tag/2.10.0. I guess this issue might be closed now.
