### ISSUE TITLE
Failing CI pipeline due to missing composer plugin allow-list

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-server#37]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | *

#### Summary

CI is red due to the fact that composer requires projects `composer.json` to explicitly allow or disallow all `composer-plugin` dependencies.

#### Current behavior

CI is red.

#### How to reproduce

Simply run `composer install` with latest composer (at least >2.3.10)

#### Expected behavior

CI is green.

**Comment by Ocramius** [comment]
Applied fix: https://github.com/laminas/laminas-server/commit/a59421970d5d3370958788194d541af740000f7e
