### ISSUE TITLE
laminas/laminas-zendframework-bridge removed without notice

### ISSUE THREAD

**Issue by jesse-deboer** [laminas/laminas-server#62]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.13.0

#### Summary

In the last update `laminas/laminas-zendframework-bridge` was removed as dependency. This is not noted anywhere in the changelog and has a huge influence on other packages that depend on it like https://github.com/magento/magento2/

#### Previous behavior

`laminas/laminas-zendframework-bridge` was included

#### Current behavior

`laminas/laminas-zendframework-bridge` is not included anymore

#### How to reproduce

Update to 2.13.0

**Comment by peterjaap** [comment]
This is the offending commit; https://github.com/laminas/laminas-server/commit/39aa12b2a7fed95b63926e4f87a94f2c60475ae2

**Comment by Ocramius** [comment]
Oh wow, no, I just saw that `2.13.0` is completely foobar'd!

It contained all `3.0.x` changes, instead of just `2.x` :scream: 

I'm releasing `2.12.0` as `2.13.1` ASAP, and will drop the `2.13.0` tag (yep, it is that bad!)

**Comment by Ocramius** [comment]
https://github.com/laminas/laminas-server/releases/tag/2.13.1 meanwhile

**Comment by jesse-deboer** [comment]
Holy shit that was fast! 🚀

**Comment by Ocramius** [comment]
The `2.13.0` tag is also removed.

I kept a backup as a branch.

 I've done what should never be done (tags should never be deleted), but I feel that the trade-off was OK here, since `2.13.0` was actively breaking everything.

Note: `2.13.0` will **NOT** be re-tagged: it is gone.

**Comment by Ocramius** [comment]
Backtracking what happened, and it was me all along:

```
commit a29cf5fd5de654c756bf36720b3b5059afee1f09
Merge: b2b1c45 ffb0b80
Author: Marco Pivetta <ocramius@gmail.com>
Date:   Mon Oct 11 15:29:23 2021 +0200

    Merge pull request #32 from ihor-sviziev/2.11.0-to-3.0.x
    
    Merge release 2.11.0 into 3.0.x

commit ffb0b80b87d46b7f8ac4e227d239aa5e1353507a
Author: Ihor Sviziev <ihor-sviziev@users.noreply.github.com>
Date:   Mon Oct 11 16:03:23 2021 +0300

    Merge release 2.11.0 into 3.0.x
    
    Fix phpcs failure
    
    Signed-off-by: Ihor Sviziev <svizev.igor@gmail.com>

commit 39aa12b2a7fed95b63926e4f87a94f2c60475ae2
Merge: 7582832 b2b1c45
Author: Ihor Sviziev <svizev.igor@gmail.com>
Date:   Fri Oct 8 11:45:45 2021 +0300

    Merge remote-tracking branch 'upstream/3.0.x' into 2.11.0-to-3.0.x
    
    Signed-off-by: Ihor Sviziev <svizev.igor@gmail.com>
```

Problematic:

 * 39aa12b2a7fed95b63926e4f87a94f2c60475ae2
 * ffb0b80b87d46b7f8ac4e227d239aa5e1353507a
 * a29cf5fd5de654c756bf36720b3b5059afee1f09

This is a merge-up from `2.x` to `3.x` gone wrong (in the wrong direction).

I'll rebuild `2.13.x` from scratch, I suppose...

**Comment by Ocramius** [comment]
Ok, `2.13.x` (branch) needs a full rollback too.

I will also spawn `2.14.x`

**Comment by Ocramius** [comment]
So, I've rolled back `2.13.x` and `2.14.x`.

This also means that PHP 8.2 support will need to be re-introduced from scratch.

Meanwhile, I had this on the `2.14.0` milestone to prevent an accidental release of that: putting it back to `2.12.1` and closing :+1:
