### ISSUE TITLE
Remove laminas/laminas-zendframework-bridge dependency

### ISSUE THREAD

**Issue by xbojer** [laminas/laminas-server#74]
### Feature Request
Remove laminas/laminas-zendframework-bridge dependency.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

laminas/laminas-zendframework-bridge is deprecated and should not be used anymore. Can this be removed from dependencies?

**Comment by froschdesign** [comment]
@xbojer 
Any help is welcome, so create a pull request for it.
Thanks in advance! 👍🏻

**Comment by Ocramius** [comment]
It can be dropped if `zendframework/zend-server` becomes a `conflict` here: https://github.com/laminas/laminas-server/blob/3b7d6528b0d696b1091f7ab76f9257ab2c87634c/composer.json#L67-L69

See for example https://github.com/laminas/laminas-stdlib/blob/f968c1bfa144f4443366d7c430919e6468cd05f4/composer.json#L61-L63

**Comment by xbojer** [comment]
Merged in #76. If someone have errors after upgrade (use old Zend namespace) I suggest requiring laminas/laminas-zendframework-bridge directly in your project.

**Comment by Ocramius** [comment]
Thanks @xbojer!
